### ISSUE TITLE
unicode characters isn't displayed correctly

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index-replicate-index-to-browser-example#1]
Special characters isn't displayed correctly, and then all words with those characters are unsearchable:
- "æ" becomes "Ã¦"
- "ø" becomes "Ã¸"
- "å" becomes "Ã¥"

Reason: Missing charset definition.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    [...] your existing code here [...]
  </body>
</html>
```

I'll make a PR

**Comment by fergiemcdowall** [comment]
OK- if you can fix this please do. The "proper" fix might be to HTML escape non-ascii chars?

**Comment by eklem** [comment]
Fixed with the proper html and meta-tag: https://github.com/fergiemcdowall/search-index-replicate-index-to-browser-example/pull/2
